name: validate the swagger api descriptions

on:
  push:
    branches:
      - v0.1.0

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - run: npm install -g openapi-examples-validator
    - run: openapi-examples-validator swagger.yaml
